# Generated by Django 5.2.4 on 2025-08-23 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=30, null=True, unique=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=30, null=True, unique=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=30, null=True, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('description_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('description_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('description_uz', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sort Order')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_en', models.TextField(null=True, verbose_name='Description')),
                ('description_ru', models.TextField(null=True, verbose_name='Description')),
                ('description_uz', models.TextField(null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('image', models.ImageField(upload_to='products', verbose_name='Image')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='products.productcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('color', models.CharField(blank=True, max_length=255, null=True, verbose_name='Color')),
                ('color_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Color')),
                ('color_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Color')),
                ('color_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Color')),
                ('size', models.CharField(blank=True, max_length=255, null=True, verbose_name='Size')),
                ('size_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Size')),
                ('size_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Size')),
                ('size_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Size')),
                ('stock', models.PositiveIntegerField(verbose_name='Stock')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='variants', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
            },
        ),
    ]
